Create a numpy array with numpy.array module and with the data type integer and float.

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5,6,7.8],dtype='int')
print(arr1)
print(arr1.dtype)

[1 2 3 4 5 6 7]
int64


In [ ]:
arr2=np.array([2,4,5,6,3.5],dtype='float')
print(arr2)
print(arr2.dtype)

[2.  4.  5.  6.  3.5]
float64


Create numpy arrays that have zero,one,two,three dimensions respectively.Also print the shape and dimension of the numpy arrays created above.

In [ ]:
'''The dimensionality of arrays=No of square bracket we used to create'''

In [ ]:
#0d-use no brackets and pass single value
arr=np.array(34)
print(arr)

#Shape of the array
print(arr.shape)

#Dimension of the array
print(arr.ndim)

34
()
0


In [ ]:
#1d-use 1 square brackets
arr=np.array([1,2,3,4,5])
print(arr)

print(arr.shape)

print(arr.ndim)

[1 2 3 4 5]
(5,)
1


In [ ]:
#2d array
arr=np.array([[1,2],[3,4]])
print(arr)

print(arr.shape)

print(arr.ndim)

[[1 2]
 [3 4]]
(2, 2)
2


In [ ]:
#3d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


Create a 2x3, 3x3, 4x4 identity matrix using numpy.

In [ ]:
#Identity Matrix-All diagonal elements will be 1 and non diagonal elements will be 0
arr=np.identity(2)    #2x2
print(arr)

arr=np.identity(3)     #3x3
print(arr)

arr=np.identity(4)    #4x4
print(arr)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr=np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


Create a numpy array with shape 2x5 that has all the elements as zero.

In [ ]:
arr=np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr=np.full((2,5),0)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


Create a numpy array that has shape 3x5 and all the elements are 5.

In [ ]:
arr=np.full((3,5),5)
print(arr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
arr=np.ones((3,5),dtype='int')*5
print(arr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Create a numpy array with random integers in the range 0-100 and the size should be 25.

In [ ]:
arr=np.random.randint(0,101,size=25)
print(arr)

[ 53  95  86   5  35  93  72  75  74  22   2  90  20  25  87  14  33  33
  47  99  34  73   0  23 100]


Create a numpy array in the shape 2x3 with random integers in the range 0-100.Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [ ]:
arr=np.random.randint(0,101,size=(2,3))
print(arr)
print(arr.shape)   #2 rows and 3 columns
newarr=arr.reshape(3,2,order='c')  #c means row wise filling and f means column wise filling
print(newarr)
print(newarr.shape) #3 rows and 2 columns

[[31  3  6]
 [ 2 38 26]]
(2, 3)
[[31  3]
 [ 6  2]
 [38 26]]
(3, 2)
