In [8]:
import numpy # if this line runs without any error --> numpy is already available

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [9]:
import xyz # there is no package called xyz so it will always throw error

ModuleNotFoundError: No module named 'xyz'

In [10]:
import Numpy

ModuleNotFoundError: No module named 'Numpy'

In [11]:
import nummpy

ModuleNotFoundError: No module named 'nummpy'

In [12]:
ModuleNotFoundError: 
1. Case sensitive 
2. Spelling 
3. Install that module from pypi website

SyntaxError: invalid syntax (3571142353.py, line 1)

In [13]:
# use this command pip install <package_name> from pypi website whenever you face modulenot found error

In [14]:
# !pip install numpy # requirement already satisfied( because numpy is already installed)
# when you use ! mark --> it opens terminal and executes your code

#### Creation of Array

In [ ]:
# arrays are not default in python 
# we use list / tuple and convert them into an array

In [15]:
import numpy
ar1 = numpy.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [16]:
type(ar1)

numpy.ndarray

In [17]:
list1 = [1,1.2,'python']
list1

[1, 1.2, 'python']

In [18]:
ar2 = numpy.array([1,1.2,'python'])
ar2

array(['1', '1.2', 'python'], dtype='<U32')

In [ ]:
# bool --> int --> float --> complex --> string
# if you have 1 string value in array entire array will be converted into strings 

In [19]:
list1 = [10,20,30,40,50]
[i**2 for i in list1]

[100, 400, 900, 1600, 2500]

In [20]:
ar1

array([1, 2, 3, 4, 5])

In [21]:
ar1**2

array([ 1,  4,  9, 16, 25])