In [1]:
import numpy 
ar1 = numpy.array([1,2,3,4,5]) # list/tuple 
ar1

array([1, 2, 3, 4, 5])

In [2]:
import numpy as np # alias name 
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [3]:
np.zeros([3,4]) # 1 parameter --> [3,4] --> shape --> no of rows and columns
# create an array with 3 rows and 4 columns and fill the array with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.random.random([3,4]) # shape parameter
# create a random array between 0 to 1

array([[0.25393748, 0.68920361, 0.14766371, 0.3946416 ],
       [0.17349261, 0.30413606, 0.63571417, 0.49299459],
       [0.82731675, 0.46492826, 0.91898179, 0.77760488]])

In [15]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



#### Initiating an array

In [16]:
np.full([3,4], 10) # 2 parameters (shape,value)
# create an array with 3 rows and 4 columns and fill the array with value 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [17]:
np.full([2,2], 'a') # u1 is representig strings 

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [18]:
range(1,5)

range(1, 5)

In [19]:
for i in range(1,5):
    print(i)

1
2
3
4


In [20]:
list(range(1,5))

[1, 2, 3, 4]

In [21]:
list(range(1,10,2)) # start , end(excluding), step (-1)
# from 1 till 10 skip 1 numbers in between 

[1, 3, 5, 7, 9]

In [22]:
np.arange(1,10,2) # array + range

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(1,10,6) # start , end (including), no.of values 
# from 1 till 10(including ) generate 6 numbers with equal interval / difference 

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [27]:
np.linspace(1,20,9)

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

#### Array Inspection

In [36]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
ar1.size # no.of elements in array

24

In [30]:
ar1.dtype

dtype('int64')

In [ ]:
# data types : python is dynamically typed programming language --> python decides data type of variable
# sql : bigint / smallint (64,32)
# numbers: int/float 
# character: strings / U

In [31]:
type(ar1)

numpy.ndarray

In [34]:
ar1.ndim # no.of dimension 

1

In [ ]:
# when you want to change dimensions use reshape
# rows * columns == size


In [40]:
ar1.size

24

In [ ]:
1*24 
2*12
3*8
4*6
.

In [38]:
ar2 = ar1.reshape(6,4) 
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [39]:
ar2.ndim

2

In [41]:
ar1.reshape(5,5)
# 5*5 != 24

ValueError: cannot reshape array of size 24 into shape (5,5)

In [42]:
ar1.reshape(3,3)
# 3*3 != 24

ValueError: cannot reshape array of size 24 into shape (3,3)

In [44]:
ar3 = ar1.reshape(3,2,4) # create 3 arrays with 2 rows and 4 columns
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [45]:
ar3.ndim

3