In [1]:
import numpy as np

In [2]:
ar1 = np.array([[10,20],[30,40]])
ar1

array([[10, 20],
       [30, 40]])

In [3]:
np.sum(ar1)

100

In [4]:
np.sum(ar1, axis = 0) # axis = 0 ; perform sum operation on rows # calculate row sum

array([40, 60])

In [5]:
np.sum(ar1, axis = 1) # axis =1; calculate column sum

array([30, 70])

In [ ]:
# axis parameter exist only in sum function 

In [7]:
print(np.subtract(20,10))
print(np.multiply(20,10))
print(np.divide(20,10))
print(np.log(20))
print(np.exp(20)) # exponential 
print(np.sqrt(20)) # square root
print(np.sin(20)) 

10
200
2.0
2.995732273553991
485165195.4097903
4.47213595499958
0.9129452507276277


In [10]:
# slicing

In [ ]:
# 1. Index will always start from zero
# 2. End value is not included

In [12]:
list1 = [10,20,30,40,50]# 20,30,40 
list1[1:4] # [start : end-1]

[20, 30, 40]

In [21]:
# if i want to extract 20,30,40,50
list1[1:5] # 

[20, 30, 40, 50]

In [22]:
list1[1:] # if end is not mentioned python will execute till end/last / available

[20, 30, 40, 50]

In [24]:
# if i want to extract 10,20,30
list1[0:3]

[10, 20, 30]

In [25]:
list1[:3] # if start is not mentioned python will execute it as 0

[10, 20, 30]

In [15]:
ar1 = np.array([10,20,30,40,50])
ar1[1:4]

array([20, 30, 40])

In [16]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [17]:
ar1[2:4,1:3] # 2:4 : 2,3 ( end is excluded )
             # 1:3 : 1,2 ( end is excluded )

array([[10, 11],
       [14, 15]])

In [19]:
ar1[2:6,0:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [23]:
ar1[2:,0:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
ar1[2:,:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [27]:
# if you want to take partition in rows with all the columns
ar1[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [28]:
# if you want to take few columns and all the rows
ar1[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [29]:
# array manipulation

In [34]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])

ar1 # 2 rows and 2 columns

array([[10, 20],
       [30, 40]])

In [35]:
np.concatenate([ar1,ar2], axis = 0) # apply function at rows

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [38]:
np.row_stack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [39]:
np.vstack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [37]:
np.concatenate([ar1,ar2], axis = 1) # apply function at columns

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [40]:
np.column_stack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [41]:
np.hstack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [44]:
ar3 = np.hstack([ar1,ar2,ar1])
ar3

array([[10, 20, 50, 60, 10, 20],
       [30, 40, 70, 80, 30, 40]])

In [45]:
np.hsplit(ar3,3) # split array into 3 equal portions

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]]),
 array([[10, 20],
        [30, 40]])]